export type BrandCatalog = {
  id: string;
  name: string;
  accent: string;
  prompt: string;
  products: string[];
};

export const brandCatalog: BrandCatalog[] = [
  {
    id: "brand-pipes",
    name: "Astral Pipes",
    accent: "brand-pipes",
    prompt: "Pipes, fittings and water systems",
    products: [
      "CPVC Pro",
      "Pex-a PRO",
      "MultiPex",
      "Aquarius",
      "ECO PRO",
      "Silencio",
      "Drain Pro",
      "Drainmaster",
      "Channel Pro",
      "Drain Hulk",
      "D-Rex",
      "Foamcore",
      "Underground",
      "Power Drain",
      "Rainway",
      "Aquasafe",
      "Bore-well",
      "Case-Well",
      "Geo-Rex",
      "Power Flex",
      "Cleo",
      "Vito",
      "Sylo",
      "Opta",
      "Delta",
      "Pio",
      "Elo",
      "Sarita",
      "Chem Pro",
      "Chem Flow",
      "Aquarius+",
      "Thermoplastic True Union Ball Valve",
      "Thermoplastic Single Union Ball Valve",
      "Thermoplastic Compact Union Ball Valve",
      "NRV",
      "Wire Guard",
      "TeleRex",
      "MultiRex",
      "Fire pro",
      "Pre-StiRex",
      "Plus+StiRex",
      "Clamps & Hangers",
      "WELD-ON",
      "Pipe Fix",
      "XLPE PRO",
      "Water Hammer Arrestor",
      "Y-STRAINER",
      "Air Admittance Valve",
      "Basin Trap",
      "Back Flow Preventer Valve",
      "Gully Trap",
    ],
  },
  {
    id: "brand-bathware",
    name: "Astral Bathware",
    accent: "brand-bathware",
    prompt: "Faucets, showers and sanitaryware",
    products: [
      "One Piece Toilets",
      "Wall Hung Toilets",
      "Two Piece Floor Mounting Toilets",
      "Two Piece Wall Hung Toilets",
      "Floor Mounting Toilets",
      "Orissa Pan",
      "Table Top Basins",
      "One Piece Basins With Integrated Pedestal",
      "Wall Hung Basins",
      "Under Counter Basins",
      "Pedestals",
      "Cisterns",
      "Urinals",
      "Accessories",
      "Basin Area",
      "Shower Area",
      "Kitchen Area",
      "Allied Products",
      "Concealed Parts",
      "Thermostatic Shower Mixer",
      "Sensors",
      "Flush Valves & Control Valves",
      "Overhead Showers",
      "Showers",
      "Complementary Products",
      "Bathroom Accessories",
      "Clinical Faucets & Pressmatics",
    ],
  },
  {
    id: "brand-adhesives",
    name: "Astral Adhesives",
    accent: "brand-adhesives",
    prompt: "Adhesives, sealants and putty",
    products: [
      "Bondtite Fast and Clear",
      "Bondtite Super Strength",
      "Bondtite Strong and Clear",
      "Bondtite Heatbond",
      "Bondtite Quick Spot-On",
      "Bondtite Quick Art & Craft",
      "Bondtite Quick Gel",
      "Bondtite Quick Ultra Glue",
      "Bondtite Deluxe",
      "Bondtite Aqua",
      "Bondtite Hydra+",
    ],
  },
  {
    id: "brand-paints",
    name: "Astral Paints",
    accent: "brand-paints",
    prompt: "Interior, exterior and wall care range",
    products: ["Interior Emulsions", "Exterior Emulsions", "Enamel", "Distemper", "Primers", "Wall Putty"],
  },
  {
    id: "brand-foundation",
    name: "Astral Foundation",
    accent: "brand-foundation",
    prompt: "CSR, conservation and reports",
    products: ["Campaign Story", "Event Album", "Report", "Social Creative"],
  },
  {
    id: "brand-corporate",
    name: "Astral Limited",
    accent: "brand-corporate",
    prompt: "Corporate, investor and group assets",
    products: ["Investor Deck", "Corporate Banner", "Annual Report", "Press Creative"],
  },
];

export const assetTypeOptions = [
  "Social Post",
  "Reel / Video",
  "Story",
  "Banner",
  "Packshot",
  "Logo",
  "Artwork",
  "Report",
];

export const platformOptions = [
  "Instagram",
  "Facebook",
  "LinkedIn",
  "YouTube",
  "Website",
  "WhatsApp",
  "Print",
  "Internal",
];

export const versionOptions = ["v1", "v2", "v3", "Final"];
