import type {
  AccessGrantRecord,
  ApprovalQueueItem,
  AppUser,
  AssetDetail,
  AssetHistoryEntry,
  AssetRecord,
  AuditEvent,
  BrandRecord,
  DashboardData,
} from "@/lib/types";

export const demoBrands: BrandRecord[] = [
  {
    id: "brand-pipes",
    slug: "astral-pipes",
    name: "Astral Pipes",
    businessUnit: "Pipes Division",
    description: "Central library for pipes creatives, packshots, trade assets, and campaign executions.",
  },
  {
    id: "brand-adhesives",
    slug: "astral-adhesives",
    name: "Astral Adhesives",
    businessUnit: "Adhesives Division",
    description: "Bondtite and adhesives workspace for social, launch, and product content.",
  },
  {
    id: "brand-bathware",
    slug: "astral-bathware",
    name: "Astral Bathware",
    businessUnit: "Bathware Division",
    description: "Lifestyle imagery, retail collateral, and product-focused bathware assets.",
  },
  {
    id: "brand-paints",
    slug: "astral-paints",
    name: "Astral Paints",
    businessUnit: "Paints Division",
    description: "Esteema and Gem brand content, campaign creatives, and shade assets.",
  },
  {
    id: "brand-foundation",
    slug: "astral-foundation",
    name: "Astral Foundation",
    businessUnit: "CSR / Conservation",
    description: "CSR events, conservation stories, and foundation reports.",
  },
  {
    id: "brand-corporate",
    slug: "astral-limited",
    name: "Astral Limited",
    businessUnit: "Corporate",
    description: "Corporate presentations, annual-report assets, and investor-facing collateral.",
  },
];

export const demoUsers: AppUser[] = [
  {
    id: "user-super-admin",
    fullName: "Super Admin",
    email: "superadmin@astral.in",
    role: "super_admin",
    primaryBrandId: null,
    grantedBrandIds: demoBrands.map((brand) => brand.id),
    isActive: true,
    mode: "demo",
  },
  {
    id: "user-pipes-admin",
    fullName: "Pipes Brand Admin",
    email: "pipes-admin@astral.in",
    role: "brand_admin",
    primaryBrandId: "brand-pipes",
    grantedBrandIds: [],
    isActive: true,
    mode: "demo",
  },
  {
    id: "user-paints-member",
    fullName: "Paints Marketing User",
    email: "paints-member@astral.in",
    role: "brand_member",
    primaryBrandId: "brand-paints",
    grantedBrandIds: [],
    isActive: true,
    mode: "demo",
  },
  {
    id: "user-agency-pro",
    fullName: "PRO Agency",
    email: "pro@agency.in",
    role: "agency_partner",
    primaryBrandId: "brand-paints",
    grantedBrandIds: [],
    isActive: true,
    agencyName: "PRO",
    accessExpiresAt: "2026-06-30T00:00:00.000Z",
    mode: "demo",
  },
];

export const demoAssets: AssetRecord[] = [
  {
    id: "asset-1",
    brandId: "brand-pipes",
    brandName: "Astral Pipes",
    brandSlug: "astral-pipes",
    title: "CPVC packshot hero",
    description: "Approved product hero for dealer channel usage.",
    category: "Packshot",
    platform: "Internal",
    campaignName: "Dealer Push Q2",
    productName: "CPVC Pro",
    fileType: "png",
    versionLabel: "v3",
    status: "approved",
    uploadedById: "user-pipes-admin",
    uploadedByName: "Pipes Brand Admin",
    tags: ["packshot", "cpvc", "dealer"],
    isShared: false,
    createdAt: "2026-04-10T11:00:00.000Z",
  },
  {
    id: "asset-2",
    brandId: "brand-paints",
    brandName: "Astral Paints",
    brandSlug: "astral-paints",
    title: "Summer shades carousel",
    description: "Pending carousel from agency for Instagram publish.",
    category: "Social Post",
    platform: "Instagram",
    campaignName: "Summer Refresh",
    productName: null,
    fileType: "psd",
    versionLabel: "v2",
    status: "pending_approval",
    uploadedById: "user-agency-pro",
    uploadedByName: "PRO Agency",
    tags: ["summer", "carousel", "instagram"],
    isShared: false,
    createdAt: "2026-04-14T09:30:00.000Z",
  },
  {
    id: "asset-3",
    brandId: "brand-corporate",
    brandName: "Astral Limited",
    brandSlug: "astral-limited",
    title: "Investor deck masthead",
    description: "Corporate header artwork for quarterly investor deck.",
    category: "Banner",
    platform: "Internal",
    campaignName: "Q1 Results",
    productName: null,
    fileType: "svg",
    versionLabel: "final",
    status: "approved",
    uploadedById: "user-super-admin",
    uploadedByName: "Super Admin",
    tags: ["corporate", "investor", "presentation"],
    isShared: false,
    createdAt: "2026-04-11T15:45:00.000Z",
  },
  {
    id: "asset-4",
    brandId: "brand-foundation",
    brandName: "Astral Foundation",
    brandSlug: "astral-foundation",
    title: "Wildlife conservation report cover",
    description: "Approved foundation report cover artwork.",
    category: "Report",
    platform: "Internal",
    campaignName: null,
    productName: null,
    fileType: "pdf",
    versionLabel: "v1",
    status: "approved",
    uploadedById: "user-super-admin",
    uploadedByName: "Super Admin",
    tags: ["csr", "report", "foundation"],
    isShared: false,
    createdAt: "2026-04-05T08:15:00.000Z",
  },
  {
    id: "asset-5",
    brandId: null,
    brandName: "Shared Library",
    brandSlug: null,
    title: "Diwali shared campaign starter",
    description: "Editable festive starter kit shared across all brands.",
    category: "Topical Day",
    platform: "Instagram",
    campaignName: "Diwali 2026",
    productName: null,
    fileType: "ai",
    versionLabel: "v1",
    status: "approved",
    uploadedById: "user-super-admin",
    uploadedByName: "Super Admin",
    tags: ["diwali", "shared", "festival"],
    isShared: true,
    createdAt: "2026-04-12T12:00:00.000Z",
  },
  {
    id: "asset-6",
    brandId: null,
    brandName: "Shared Library",
    brandSlug: null,
    title: "World Water Day explainer key visual",
    description: "Shared sustainability creative for all brand teams.",
    category: "Topical Day",
    platform: "LinkedIn",
    campaignName: "World Water Day",
    productName: null,
    fileType: "png",
    versionLabel: "final",
    status: "approved",
    uploadedById: "user-super-admin",
    uploadedByName: "Super Admin",
    tags: ["water-day", "shared", "environment"],
    isShared: true,
    createdAt: "2026-04-13T10:00:00.000Z",
  },
];

export const demoApprovalQueue: ApprovalQueueItem[] = [
  {
    id: "approval-1",
    assetId: "asset-2",
    assetTitle: "Summer shades carousel",
    brandName: "Astral Paints",
    uploadedByName: "PRO Agency",
    reviewerRole: "super_admin",
    category: "Social Post",
    platform: "Instagram",
    versionLabel: "v2",
    submittedAt: "2026-04-14T09:30:00.000Z",
    comment: "Awaiting visual review from Paints team.",
  },
];

export const demoAuditEvents: AuditEvent[] = [
  {
    id: "audit-1",
    eventType: "upload",
    title: "Agency upload submitted",
    summary: "PRO Agency uploaded Summer shades carousel to Astral Paints and routed it to pending approval.",
    actorName: "PRO Agency",
    brandName: "Astral Paints",
    entityTitle: "Summer shades carousel",
    createdAt: "2026-04-14T09:35:00.000Z",
  },
  {
    id: "audit-2",
    eventType: "approval",
    title: "Shared asset approved",
    summary: "World Water Day explainer key visual published into the shared library for all brands.",
    actorName: "Super Admin",
    brandName: "Shared Library",
    entityTitle: "World Water Day explainer key visual",
    createdAt: "2026-04-13T10:30:00.000Z",
  },
  {
    id: "audit-3",
    eventType: "grant",
    title: "Cross-brand read access granted",
    summary: "Astral Foundation received read-only access to Astral Pipes for a co-branded sustainability initiative.",
    actorName: "Super Admin",
    brandName: "Astral Foundation",
    entityTitle: "Astral Pipes access",
    createdAt: "2026-04-09T17:00:00.000Z",
  },
];

export const demoDashboardData: DashboardData = {
  approvedCount: demoAssets.filter((asset) => asset.status === "approved").length,
  pendingCount: demoAssets.filter((asset) => asset.status === "pending_approval").length,
  brandsCount: demoBrands.length,
  sharedAssetsCount: demoAssets.filter((asset) => asset.isShared).length,
  latestAssets: demoAssets.slice(0, 5),
  recentActivity: demoAuditEvents,
};

export const demoAccessGrants: AccessGrantRecord[] = [
  {
    id: "grant-1",
    userId: "user-pipes-admin",
    userName: "Pipes Brand Admin",
    userEmail: "pipes-admin@astral.in",
    brandId: "brand-foundation",
    brandName: "Astral Foundation",
    grantedAt: "2026-04-09T17:00:00.000Z",
    grantedByName: "Super Admin",
  },
];

export const demoAssetHistory: Record<string, AssetHistoryEntry[]> = {
  "asset-1": [
    {
      id: "history-1",
      type: "version",
      title: "Version v3 uploaded",
      summary: "Updated packshot approved for dealer distribution.",
      createdAt: "2026-04-10T11:00:00.000Z",
    },
    {
      id: "history-2",
      type: "download",
      title: "Downloaded",
      summary: "Downloaded by Pipes Brand Admin as original PNG.",
      createdAt: "2026-04-12T16:20:00.000Z",
    },
  ],
  "asset-2": [
    {
      id: "history-3",
      type: "version",
      title: "Version v2 uploaded",
      summary: "Agency uploaded revised carousel for review.",
      createdAt: "2026-04-14T09:30:00.000Z",
    },
    {
      id: "history-4",
      type: "approval",
      title: "Waiting for approval",
      summary: "Queued for Paints review with agency note.",
      createdAt: "2026-04-14T09:35:00.000Z",
    },
  ],
};

export const demoAssetDetails: Record<string, AssetDetail> = Object.fromEntries(
  demoAssets.map((asset) => [
    asset.id,
    {
      asset,
      history: demoAssetHistory[asset.id] ?? [],
    },
  ]),
);
